### ISSUE TITLE
Crear función de notificación  para supervisores

### ISSUE THREAD

**Issue by jignaciol** [sistemashcapp/OsticketNotificador#5]
Colocar una opcion para que luego de 4 horas de tener un ticket abierto se le notifique al supervisor de area. para que este informado.

**Comment by jignaciol** [comment]
Para esta opcion se crearon dos  metodos nuevos:

* numero_supervisor: que recibe un ticket existente en la base de datos local y compara el campo "departamento" del ticket y lo compara contra un diccionario donde estan lo departamentos con el id del supervisor

* buscar_info_contacto: que recibe un staff_id y con este consulta la base de datos del OSTicket y devuelve el email , telefono extension y celular del supervisor.

**Comment by jignaciol** [comment]
Hay que revisar la funcion de conteo de tiempo esta dando un salto errado de tiempo T a 0.

**Comment by foxcarlos** [comment]
Esta interesante, sólo que debería decir al menos el nombre de a quién se le asignó esa ODS para uno poder llamar y darle látigo, xq es posible que no se encuentre frente al pc en ese momento

**Comment by jignaciol** [comment]
si es correcto se lo voy a agregar.

**Comment by jignaciol** [comment]
Ya agregue el nombre de la persona que tiene asignado el caso. el mensaje queda asi:

BOT_OSTICKET: ODS #616575 asignada a Daniel Rubio,  tiene 27266 minutos de creado y no ha sido cerrado

**Comment by jignaciol** [comment]
con el commit 539a8fa queda cerrado este issue
