### ISSUE TITLE
Crear condicion para envio de mensaje de ticket al grupo

### ISSUE THREAD

**Issue by jignaciol** [sistemashcapp/OsticketNotificador#6]
Existen casos en los que un ticket se crea y es asignado al grupo de trabajo ej. Desarrollo de aplicaciones. En estos casos el mensaje se debe enviar a todos los miembros de un equipo

**Comment by foxcarlos** [comment]
Esta bien eso, entonces debemos asumir entonces que cuando no me lleguen más mensajes de esa ods es xq o fue cerrado o ya fue tomado por alguien, si es así, esta fino

**Comment by jignaciol** [comment]
segun lo pense no. como al principio no tiene alguien asignado entonces mientras no tenga nadie asignado se envian mensajes al grupo hasta que alguien lo tome entonces a partir de ahi solo le llegarian mensajes al que se asigno el ticket.

**Comment by foxcarlos** [comment]
Correcto eso fue lo.Que quise decir

**Comment by jignaciol** [comment]
ya se hicieron las prubas para esto y quedo asi 

1.- el ticket se geenera sin asignacion osea con staff_id = 0
2.- esto dispara el notificador de grupo y le envia un mensaje a todos los integrantes del grupo
3.- cuando algun integrante del grupo comenta ese ticket el osticket se lo asigna 
4.- de este punto en adelante el bot notificador notifica a esa persona y lo registra en la base de datos de control.
